cxxflags = '-std=c++11 -Wall -Wextra -Wshadow -Woverloaded-virtual -Wnon-virtual-dtor -Wno-reorder -g'
linkflags = '-g'
libs = 'glog'

def options(opt):
    opt.load('compiler_cxx unittest_gtest')

def configure(conf):
    conf.load('compiler_cxx unittest_gtest')
    conf.check_cxx(cxxflags=cxxflags)
    conf.check_cxx(linkflags=linkflags)
    conf.check_cxx(lib=libs)

def build(bld):
    bld.program(
            features='gtest',
            source=[
                'binary_cube_test.cpp',
                'extractor_test.cpp',
                ],
            target='test',
            includes='. ../src',
            use='sigen',
            cxxflags=cxxflags,
            linkflags=linkflags,
            lib=libs,
            uselib='opencv')

# vim: filetype=python
