def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.stlib(
        source=[
            'common/binary_cube.cpp',
            'common/disjoint_set.cpp',
            'common/neuron.cpp',
            'common/voxel.cpp',
            'common/cluster.cpp',
            'loader/file_loader.cpp',
            'binarizer/binarizer.cpp',
            'extractor/extractor.cpp',
            'builder/builder.cpp',
            'writer/swc_writer.cpp',
            'writer/fileutils.cpp',
        ],
        target='sigen')
    bld.program(
        source='main.cpp',
        target='main',
        includes='../third_party',
        use='sigen OPENCV BOOST_SYSTEM BOOST_FILESYSTEM GLOG')

# vim: filetype=python
