def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.stlib(
        source=[
            'common/binary_cube.cpp',
            'common/disjoint_set.cpp',
            'common/neuron.cpp',
            'common/voxel.cpp',
            'common/cluster.cpp',
            'binarizer/binarizer.cpp',
            'extractor/extractor.cpp',
            'builder/builder.cpp',
        ],
        target='sigen_core')

# vim: filetype=python
