def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.stlib(
        source=[
            'loader/file_loader.cpp',
            'writer/swc_writer.cpp',
            'writer/fileutils.cpp',
            'binarizer/binarizer.cpp',
        ],
        target='sigen_io',
        includes='. ../sigen_core')
    bld.program(
        source=[
            'main.cpp'
        ],
        target='main',
        includes='../third_party ../sigen_core',
        use='sigen sigen_io OPENCV BOOST_SYSTEM BOOST_FILESYSTEM GLOG')

# vim: filetype=python
