cxxflags = '-std=c++11 -Wall -Wextra -Wshadow -Woverloaded-virtual -Wnon-virtual-dtor -Wno-reorder -g'
linkflags = '-g'
libs = 'boost_system boost_filesystem glog'

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')
    conf.check_cxx(cxxflags=cxxflags)
    conf.check_cxx(linkflags=linkflags)
    conf.check_cxx(lib=libs)
    conf.check_cfg(
            package='opencv',
            args='--cflags --libs',
            uselib_store='opencv')

def build(bld):
    bld.stlib(
            source=[
                'reader/file_reader.cpp',
                'binarizer/binarizer.cpp',
                'common/binary_cube.cpp',
                'extractor/extractor.cpp',
                'extractor/point.cpp',
                ],
            target='sigen',
            includes='.',
            cxxflags=cxxflags,
            linkflags=linkflags,
            lib=libs,
            uselib='opencv')

    bld.program(
            source='main.cpp',
            target='main',
            includes='. ../third_party',
            cxxflags=cxxflags,
            linkflags=linkflags,
            lib=libs,
            use='sigen',
            uselib='opencv')

# vim: filetype=python
